"""empty message

Revision ID: 19658ea08b9a
Revises: 447cbf7110cd
Create Date: 2018-04-22 08:24:19.294586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19658ea08b9a'
down_revision = '447cbf7110cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('subtotal', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'subtotal')
    # ### end Alembic commands ###
