"""empty message

Revision ID: 3b5dd2270b10
Revises: e3ec470e36fc
Create Date: 2018-04-18 18:33:36.241624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b5dd2270b10'
down_revision = 'e3ec470e36fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('true_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'true_price')
    # ### end Alembic commands ###
