"""empty message

Revision ID: 447cbf7110cd
Revises: 53ff920698f4
Create Date: 2018-04-21 17:08:13.072352

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '447cbf7110cd'
down_revision = '53ff920698f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('status', sa.Integer(), nullable=True))
    op.add_column('orderinfo', sa.Column('order_id', sa.Integer(), nullable=True))
    op.add_column('orderinfo', sa.Column('product_name', sa.String(length=100), nullable=True))
    op.add_column('orderinfo', sa.Column('product_price', sa.Float(), nullable=True))
    op.drop_constraint('orderinfo_ibfk_1', 'orderinfo', type_='foreignkey')
    op.create_foreign_key(None, 'orderinfo', 'order', ['order_id'], ['id'])
    op.drop_column('orderinfo', 'price')
    op.drop_column('orderinfo', 'total')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orderinfo', sa.Column('total', mysql.FLOAT(), nullable=True))
    op.add_column('orderinfo', sa.Column('price', mysql.FLOAT(), nullable=True))
    op.drop_constraint(None, 'orderinfo', type_='foreignkey')
    op.create_foreign_key('orderinfo_ibfk_1', 'orderinfo', 'order', ['id'], ['id'])
    op.drop_column('orderinfo', 'product_price')
    op.drop_column('orderinfo', 'product_name')
    op.drop_column('orderinfo', 'order_id')
    op.drop_column('order', 'status')
    # ### end Alembic commands ###
