"""empty message

Revision ID: 4e8addbff67d
Revises: 9a9757ebe420
Create Date: 2018-04-22 09:28:44.232577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e8addbff67d'
down_revision = '9a9757ebe420'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'orderinfo', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orderinfo', type_='unique')
    # ### end Alembic commands ###
