"""empty message

Revision ID: 62bbbde9db7c
Revises: 19658ea08b9a
Create Date: 2018-04-22 08:26:44.241867

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '62bbbde9db7c'
down_revision = '19658ea08b9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'subtotal')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('subtotal', mysql.FLOAT(), nullable=True))
    # ### end Alembic commands ###
