"""empty message

Revision ID: 65bd590f11a2
Revises: 17bb0c32df5e
Create Date: 2018-04-16 19:58:36.396928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65bd590f11a2'
down_revision = '17bb0c32df5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('pic', table_name='product')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('pic', 'product', ['pic'], unique=True)
    # ### end Alembic commands ###
