"""empty message

Revision ID: 6ee932f497b3
Revises: 765d24756e76
Create Date: 2018-04-10 23:04:59.996672

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6ee932f497b3'
down_revision = '765d24756e76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('head_img', sa.String(length=255), nullable=True))
    op.drop_index('pic', table_name='product')
    op.create_unique_constraint(None, 'product', ['head_img'])
    op.drop_column('product', 'pic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('pic', mysql.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'product', type_='unique')
    op.create_index('pic', 'product', ['pic'], unique=True)
    op.drop_column('product', 'head_img')
    # ### end Alembic commands ###
