"""empty message

Revision ID: 7461368eb840
Revises: 7796b558971e
Create Date: 2018-04-13 23:19:32.546598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7461368eb840'
down_revision = '7796b558971e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'description')
    # ### end Alembic commands ###
