"""empty message

Revision ID: 765d24756e76
Revises: 4c824ea9625e
Create Date: 2018-04-09 20:54:58.675006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '765d24756e76'
down_revision = '4c824ea9625e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('info', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'info')
    # ### end Alembic commands ###
