"""empty message

Revision ID: 7796b558971e
Revises: f4135075d337
Create Date: 2018-04-12 10:31:22.283943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7796b558971e'
down_revision = 'f4135075d337'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('old_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'old_price')
    # ### end Alembic commands ###
