"""empty message

Revision ID: 9fe13968ba82
Revises: 62bbbde9db7c
Create Date: 2018-04-22 08:29:41.671676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fe13968ba82'
down_revision = '62bbbde9db7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('subTotal', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'subTotal')
    # ### end Alembic commands ###
