"""empty message

Revision ID: cdadde0b884f
Revises: 6ee932f497b3
Create Date: 2018-04-10 23:11:10.347184

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cdadde0b884f'
down_revision = '6ee932f497b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('pic', sa.String(length=255), nullable=True))
    op.drop_index('head_img', table_name='product')
    op.create_unique_constraint(None, 'product', ['pic'])
    op.drop_column('product', 'head_img')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('head_img', mysql.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'product', type_='unique')
    op.create_index('head_img', 'product', ['head_img'], unique=True)
    op.drop_column('product', 'pic')
    # ### end Alembic commands ###
