"""empty message

Revision ID: e9f3f8be5b27
Revises: 2223d53ce2c8
Create Date: 2018-04-09 13:57:40.043324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9f3f8be5b27'
down_revision = '2223d53ce2c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('sell', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'sell')
    # ### end Alembic commands ###
