"""empty message

Revision ID: f4135075d337
Revises: cdadde0b884f
Create Date: 2018-04-12 09:28:25.978358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4135075d337'
down_revision = 'cdadde0b884f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('view_num', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'view_num')
    # ### end Alembic commands ###
